# fly.toml app configuration file generated for app-sjebww on 2026-10-05T16:37:42Z
#
# See https://docs.fly.io/reference/configuration for information about how to use this file.
#

app = 'app-sjebww'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[restart]]
  policy = 'always'
  processes = ['app']
  retries = 10
