app = "united-cyber"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  APACHE_DOCUMENT_ROOT = "/var/www/html"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1


[checks]
  [checks.http]
    type = "http"
    port = 80
    path = "/index.php?action=check"
    interval = "30s"
    timeout = "5s"
    grace_period = "15s"
